#Read in the file 
data <- read.csv('project-data.csv')
eyes_open <- data$eyes.open
eyes_open <- eyes_open[1:40]
eyes_closed <- data$eyes.closed
eyes_closed_abs <- abs(eyes_closed)
eyes_open_abs <- abs(eyes_open)
summary(eyes_closed_abs)
summary(eyes_open_abs)
boxplot(eyes_closed_abs)
boxplot(eyes_open_abs)
hist(eyes_open)
hist(eyes_closed)
sd(eyes_closed_abs,na.rm = TRUE)
sd(eyes_open_abs,na.rm = TRUE)

eoo <- c()
eoc <- c()
ecc <- c()
eco <- c()
eoo <- append(eoo,eyes_open[1:5])
eoo <- append(eoo,eyes_open[11:15])
eoo <- append(eoo,eyes_open[21:25])
eoo <- append(eoo,eyes_open[31:35])
summary(abs(eoo))
sd(abs(eoo))
eoc <- append(eoc,eyes_open[6:10])
eoc <- append(eoc,eyes_open[16:20])
eoc <- append(eoc,eyes_open[26:30])
eoc <- append(eoc,eyes_open[36:40])
summary(abs(eoc))
sd(abs(eoc))
ecc <- append(ecc,eyes_closed[1:5])
ecc <- append(ecc,eyes_closed[11:15])
ecc <- append(ecc,eyes_closed[21:25])
ecc <- append(ecc,eyes_closed[31:35])
ecc <- append(ecc,eyes_closed[41:45])
summary(abs(ecc))
sd(abs(ecc))
eco <- append(eco,eyes_closed[6:10])
eco <- append(eco,eyes_closed[16:20])
eco <- append(eco,eyes_closed[26:30])
eco <- append(eco,eyes_closed[36:40])
eco <- append(eco,eyes_closed[46:50])
eco
summary(abs(eco))
sd(abs(eco))
# t-tests
t.test(abs(eco),abs(eoo))
t.test(abs(ecc),abs(eoc))
t.test(abs(eyes_open),abs(eyes_closed))
boxplot(abs(eoo),abs(eoc),abs(eco),abs(ecc),main = 'Overview of Eyes Open/Closed',xlab ='Start positon/eyes open/closed',ylab = 'Absolute Error(cm)',col = (c('gold','darkgreen')))
cor(abs(eoc),abs(ecc[1:20]))
cor(abs(eoo),abs(eco[1:20]))
VEE = c(var(eyes_open[1:5]),var(eyes_open[11:15]),var(eyes_open[21:25]),var(eyes_open[31:35]),var(eyes_closed[6:10]),var(eyes_closed[16:20]),var(eyes_closed[26:30]),var(eyes_closed[36:40]),var(eyes_closed[46:50]))
VEE = VEE/10
mean(VEE)
VEC = c(var(eyes_closed[1:5]),var(eyes_closed[11:15]),var(eyes_closed[21:25]),var(eyes_closed[31:35]),var(eyes_closed[41:45]),var(eyes_open[6:10]),var(eyes_open[16:20]),var(eyes_open[26:30]),var(eyes_open[36:40]))
VEC = VEC/10
mean(VEC)
par(mfrow=c(1,2))
scatter.smooth(VEE,main = 'Eyes Open',col = 'green')
scatter.smooth(VEC,main = 'Eyes Closed',col = 'blue')
#lines(VEE,col = 'green')


